import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const word = ['P', 'E', 'O', 'P', 'L', 'E']

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="container">
        <div class="game-board">
          <div class="box">
            <div class="letter">{word[0]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <div class="letter">{word[1]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <div class="letter">{word[2]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <div class="letter">{word[3]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <div class="letter">{word[4]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <div class="letter">{word[5]}</div>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
          <div class="box">
            <input></input>
          </div>
        </div>
      </div>
    </div>
  )
}

// {/* <div class="letter">{word[0]}</div> */}
